# Author: Alessandra Fais
# Date:   July 2019

# input file path
cm.spout.path=../../Datasets/CM/google-cluster-data.txt

# execution time length
cm.runtime_sec=60

# model parameters
cm.filter.targetField=3
cm.window.size=30
cm.window.slide=5

